### ISSUE TITLE
ProjectAにて、ローカルのJSONファイルを使ってCRUDができるようにしたい

### ISSUE THREAD

**Issue by sinshutu** [nagaminenot/projectA#1]

**Comment by nagamine-git** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ProjectAにて、ローカルのJSONファイルを使ってCRUDができるようにしたい](https://trello.com/c/b0Us44kA/18-projecta%E3%81%AB%E3%81%A6%E3%80%81%E3%83%AD%E3%83%BC%E3%82%AB%E3%83%AB%E3%81%AEjson%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%82%92%E4%BD%BF%E3%81%A3%E3%81%A6crud%E3%81%8C%E3%81%A7%E3%81%8D%E3%82%8B%E3%82%88%E3%81%86%E3%81%AB%E3%81%97%E3%81%9F%E3%81%84)
